Public Class NativeOrigin
    Public Shared ReadOnly Property NativeOrigins As List(Of Nuctions.Feature)
        Get
            Return New List(Of Nuctions.Feature) From {SC101, R6Kγ, p15a, N15, pUC}
        End Get
    End Property
    Public Shared ReadOnly Property SC101 As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("SC101", _SC101, "SC101", "rep_origin", "SC101 Origin")
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property R6Kγ As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("R6Kγ", _R6Kγ, "R6Kγ", "rep_origin", "R6Kγ Origin")
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property p15a As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("p15a", _p15a, "p15a", "rep_origin", "p15a Origin")
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property N15 As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("N15", _N15, "N15", "rep_origin", "N15 Origin")
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property pUC As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("pUC", _pUC, "pUC", "rep_origin", "pUC Origin")
            Return ft
        End Get
    End Property
    Private Const _SC101 As String = "CCGAGCTTGCGAGGGTGCTACTTAAGCCTTTAGGGTTTTAAGGTCTGTTTTGTAGAGGAGCAAACAGCGTTTGCGACATCCTTTTGTAATACTGCGGAACTGACTAAAGTAGTGAGTTATACACAGGGCTGGGATCTATTCTTTTTATCTTTTTTTATTCTTTCTTTATTCTATAAATTATAACCACTTGAATATAAACAAAAAAAACACACAAAGGTCTAGCGGAATTTACAGAGGGTCTAGCAGAATTTACAAGTTTTCCAGCAAAGGTCTAGCAGAATTTACAGATACCCACAACTCAAAGGAAAAGGACTAGTAATTATCATTGACTAGCCCATCTCAATTGGTATAGTGATTAAAATCACCTAGACCAATTGAGA"
    Private Const _R6Kγ As String = "AAAATTGCTTTGAGAGGCTCTAAGGGCTTCTCAGTGCGTTACATCCCTGGCTTGTTGTCCACAACCGTTAAACCTTAAAAGCTTTAAAAGCCTTATATATTCTTTTTTTTCTTATAAAACTTAAAACCTTAGAGGCTATTTAAGTTGCTGATTTATATTAATTTTATTGTTCAAACATGAGAGCTTAGTACGTGAAACATGAGAGCTTAGTACGTTAGCCATGAGAGCTTAGTACGTTAGCCATGAGGGTTTAGTTCGTTAAACATGAGAGCTTAGTACGTTAAACATGAGAGCTTAGTACGTGAAACATGAGAGCTTAGTACGTACTATCAACAGGTTGAACTGC"
    Private Const _p15a As String = "CCGCGGCAAAGCCGTTTTTCCATAGGCTCCGCCCCCCTGACAAGCATCACGAAATCTGACGCTCAAATCAGTGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGCGGCTCCCTCGTGCGCTCTCCTGTTCCTGCCTTTCGGTTTACCGGTGTCATTCCGCTGTTATGGCCGCGTTTGTCTCATTCCACGCCTGACACTCAGTTCCGGGTAGGCAGTTCGCTCCAAGCTGGACTGTATGCACGAACCCCCCGTTCAGTCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGAAAGACATGCAAAAGCACCACTGGCAGCAGCCACTGGTAATTGATTTAGAGGAGTTAGTCTTGAAGTCATGCGCCGGTTAAGGCTAAACTGAAAGGACAAGTTTTGGTGACTGCGCTCCTCCAAGCCAGTTACCTCGGTTCAAAGAGTTGGTAGCTCAGAGAACCTTCGAAAAACCGCCCTGCAAGGCGGTTTTTTCGTTTTCAGAGCAAGAGATTACGCGCAGACCAAAACGATCTCAAGAAGATCATCTTATTAATCAGATAAAATATTTCTAGA"
    Private Const _N15 As String = "CTGTTTTGGATCGAGGGTTACCATGTATATCTATATTTAGATCCAAATCGCGATCCACTTCGATGGTGGTTTTTTCCACCTTACGTGCGT"
    Private Const _pUC As String = "AAAGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTCCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCG"
End Class

Public Class NativeAntibioticResistance
    Public Shared ReadOnly Property NativeAntibioticResistances As List(Of Nuctions.Feature)
        Get
            Return New List(Of Nuctions.Feature) From {amp, kan, chl}
        End Get
    End Property
    Public Shared ReadOnly Property amp As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("amp", _amp, "amp", "CDS", "Ampicilin Resistance")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.AntibioticsResistance, .Parameters = "amp"})
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property kan As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("kan", _kan, "kan", "CDS", "Kanamycin Resistance")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.AntibioticsResistance, .Parameters = "kan"})
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property chl As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("chl", _chl, "chl", "CDS", "Chloraphenicol Resistance")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.AntibioticsResistance, .Parameters = "chl"})
            Return ft
        End Get
    End Property
    Private Const _amp As String = "ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAA"
    Private Const _kan As String = "ATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTAA"
    Private Const _chl As String = "ATGGAGAAAAAAATCACTGGATATACCACCGTTGATATATCCCAATGGCATCGTAAAGAACATTTTGAGGCATTTCAGTCAGTTGCTCAATGTACCTATAACCAGACCGTTCAGCTGGATATTACGGCCTTTTTAAAGACCGTAAAGAAAAATAAGCACAAGTTTTATCCGGCCTTTATTCACATTCTTGCCCGCCTGATGAATGCTCATCCGGAATTACGTATGGCAATGAAAGACGGTGAGCTGGTGATATGGGATAGTGTTCACCCTTGTTACACCGTTTTCCATGAGCAAACTGAAACGTTTTCATCGCTCTGGAGTGAATACCACGACGATTTCCGGCAGTTTCTACACATATATTCGCAAGATGTGGCGTGTTACGGTGAAAACCTGGCCTATTTCCCTAAAGGGTTTATTGAGAATATGTTTTTCGTCTCAGCCAATCCCTGGGTGAGTTTCACCAGTTTTGATTTAAACGTGGCCAATATGGACAACTTCTTCGCCCCCGTTTTCACCATGGGCAAATATTATACGCAAGGCGACAAGGTGCTGATGCCGCTGGCGATTCAGGTTCATCATGCCGTTTGTGATGGCTTCCATGTCGGCAGATGCTTAATGAATACAACAGTACTGCGATGA"
End Class

Public Class NativePrimase
    Public Shared ReadOnly Property NativePrimases As List(Of Nuctions.Feature)
        Get
            Return New List(Of Nuctions.Feature) From {pir, repAN15, repASC101ts1, repASC101ts2}
        End Get
    End Property
    Public Shared ReadOnly Property pir As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("pir", _pir, "pir", "CDS", "Primase for R6Kγ")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "R6Kγ"})
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property repAN15 As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("repAN15", _repAN15, "repAN15", "CDS", "Primase for N15")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "N15"})
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property repASC101ts1 As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("repASC101ts1", _repASC101ts1, "repASC101ts1", "CDS", "Primase for SC101")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "SC101"})
            Return ft
        End Get
    End Property
    Public Shared ReadOnly Property repASC101ts2 As Nuctions.Feature
        Get
            Dim ft As New Nuctions.Feature("repASC101ts2", _repASC101ts2, "repASC101ts2", "CDS", "Primase for SC101")
            ft.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "SC101"})
            Return ft
        End Get
    End Property
    Private Const _pir As String = "ATGCGTCTGAAAGTTATGATGGACGTTAACAAAAAAACCAAAATCCGTCACCGTAACGAACTGAACCACACCCTGGCGCAGCTGCCGCTGCCGGCGAAACGTGTTATGTACATGGCGCTGGCGCTGATCGACTCTAAAGAACCGCTGGAACGTGGTCGTGTTTTCAAAATCCGTGCGGAAGACCTGGCGGCGCTGGCGAAAATCACCCCGTCTCTGGCGTACCGTCAGCTGAAAGAAGGTGGTAAACTGCTGGGTGCGTCTAAAATCTCTCTGCGTGGTGACGACATCATCGCGCTGGCGAAAGAACTGAACCTGCTGTCTACCGCGAAAAACTCTTCTGAAGAACTGGACCTGAACATCATCGAATGGATCGCGTACTCTCCGGACGAAGGTTACCTGTCTCTGAAATTCACCCGTACCATCGAACCGTACATCTCTTCTCTGATCGGTAAAAAAAACAAATTCACCACCCAGCTGCTGACCGCGTCTCTGCGTCTGTCTTCTCAGTACTCTTCTTCTCTGTACCAGCTGATCCGTAAACACTACTCTAACTTCAAAAAAAAAAACTACTTCATCATCTCTGTTGACGAACTGAAAGAAGAACTGATCGCGTACACCTTCGACAAAGACGGTAACATCGAATACAAATACCCGGACTTCCCGATCTTCAAACGTGACGTTCTGAACAAAGCGATCGCGGAAATCAAAAAAAAAACCGAAATCTCTTTCGTTGGTTTCACCGTTCACGAAAAAGAAGGTCGTAAAATCTCTAAACTGAAATTTGAATTTGTGGTGGATGAAGATGAATTTTCTGGTGACAAAGACGACGAAGCGTTCTTCATGAACCTGTCTGAAGCGGACGCGGCGTTCCTGAAAGTTTTCAACGAAACCGTTCCGCCGAAAAAAGCGAAAGGTTAG"
    Private Const _repAN15 As String = "ATGACCTTACAAGAATTCTACGCGGAGCGCTTTGGCAGCGATCCGTTTTCACTGCTTGACGCGGCACGTGATGAGCTGACTGAGCTGGCGAAGATGGCCGGTATCAACTGGCCTGCGTGTGCTGATAAGATTCAGCTCAATCCGCGCGGTGGTGTAGAGCGCTATACCACCTACAATAATTCCTCCCCGGAAGCTCTGCAGAAGAGCCTTAAAGGCCGTGTGGAAATCTATTCACGCCTTGAGCAGAGCAAGGATGGCATCAGTTATCCTTTCGTTAACTTCGTTGAAAAAGCGCATGACGCTGGCTCCTGGAGTGGCTTTTCATTCCTGTTTTCGGAGTATCGCCGTGAACAGCAACGGAATGGTGCGACCGTGGTCGCTCAGCCGGAAGAAGAACGTGCACGCATGGAGCGCCAGGCTGAAGCACGCCGCCTCCGAGCTGAACAACAACGCGTTAATGATTTAAAAAACAATCAGATGGAGCAGGAACGCCTGCTTGGATGGTTGGCTTTCCATCGCGCCTGGGAACATTCGCCAGCTGAAGATGGCTCCTGGCCTTATGCGGTAAAAAAGGGAATTCGTGACGTATTTGGCGCTTGTGATATACGTCGCGTGACCAGTCACGACAGTGCGAAATGGAGCCGTGGACCAACAACTTACATGGCGATACCTCTGTCCCACCTGGACGGAAGAAAAGACGGGCGGATTGTTGGCTGGCAACGTATCGATCTGAATGGTGGCAAGTTCCAGACCAGCGCCATCACTAACGGTGATTTCGTCGGTGCATGCTTTGTTATTGGCGACCTGCAGGGGGCGCAAAAAATTGCGACTGCAGAGGGTTTCGCCACCGGGGCATCCATCTGGCTGGCGACCAGAAACGACCCGAAAAAACGCTTTGACGCGGTAGTCATTGCGGTTTCCGCTAACAACATGATTCACGTTGTCGAGCAGCTGGTGAACATGTACCCGGCTGCGCAAATCACTTGCGCTCTCGATAACGACCGCAAATCCTCAGCTGAAGGAAAAGGCAACACAGGCCTCCGCACCGGATTCGACATCATGGAGAAGTTTTCCGGCGTCAAATGTGTTTACCCAACTTTTGAGGATGACCCTGAGCTGGAATGCAGCGATTTTAACGACCTGCACAGCCTGAGAGGGCTGAAGGAAGTCGCTCGCCAGTTAACGAGAAATCATCTGAGCCGTGCAACCGATCTGTTGTCGATCACGCTGAATAAGCTGCGTACTCTCCCGCGTCTGAACAGACGCACTTTTGCCAAAGAACTGCTTCGCGCCGTTGATATTGGCATGCTGACATGCCCGGTACCAAACAGCCCGAAAGAACTTATGCGCCTTTTCAGCAGCACGCTGCGGGATATGGGTATCGCAGAAATTTATAACGGTACCGTTAAAGATCACATTACGCGCCGGTTGAATCGCAAATGCCGTGCCGCGCAAACATCACGTTCGTTCAGTGAACGCATCACCAACCCGAACCTTCGCCCGTCACACATCACTTACAAACGGTTTGAAACCTCCAGGATGACCGATGAGGTGATGACATACGCCGCACAGCTGCAGGGCATCGTTATTGTCCGCGCCGGGATGGGGTCGGGTAAATCGACAGGCCTCCTGCGTCCACTGATGCTGCAGTCCACGCGTGGCGTTTCCGTCGCGCACCGCGTATCCCTGATAGGCGGCCTGCATGAAATGATGACCGAAGGGAAAGGCGCGAAAGCCGACATTCTGCATTATCAGGATCCCGGCTATCAGGAAATGGCGCCATATGCCAACAAGCTGACTATTTGCATCAACTCCATACTTAAAGGCTGCTGGCAACCGCTGATGCGCCAGCATGACTTCTTCGGCTTCGATGAAGCAACACAGGGCCTGCGTGCCATTCTGGCCGGGCGTGCGATGGAAAACCCGGTAGGCGTATTCAACACGCTTATCGACGCGCTGGCGCGTACTGAAGAGCATGCCATTATGGTGGATGCCGATGCCAACGATCTGCTTGTTGACCTGGCTGAACTGGCGATGAAGCGACGCGAGGAGCTGGGCCTACCTGCCTGGCTGCAAATTCACGTGATTGAACTCCCGGTCGACGTTCGCAACCGCGAAACCAACAAGCCTATCCGCGTATTTTATACCGAGAAAAATCGGATCATGACCGAGGTTATCGCTGCAGTGCAACGCGGCGAACGAATCATGCTGGCCACCGACAGTTCGACGTTCGCCGAAGACGTTACCATGCAGCTGAGACTACAGTTCCCTGACAAAAAGTTTCTCTGCGTTAACCAGAAAAACAAACAGGAGAAGGAAGTCGACGATTTCACCAACCAGCCTAAAGTGATGGTGAAAAAATATGACGGCCTCATCTACAGCCCGTCGATATCTTCAGGTGTATCGATTGAGGAGAAACACTTCCACCGCCATTTCGGCATGTTCTGCGGCGAAGTGGTCCCCAGCGACGCCATCCAGATGCTGCGCCGCGACCGTACAGCTCAGGAATACATTATCGGTTTCGACAAGCTTCGCGGTAAACGTGAAACCGATCCGGAAAAAATCAAACGCGCCTACGCGCAGGCCTTGCTCGAAACGGCTGGCCACTCCGGGCTGCTGACAGACGTTGTCTTTGACGGTGACCGAATTTCACTCGGCGTGGCTAACTCTTCATTCATGCAGCTCAAAATTAAAGCCGCCGCGCTCGAGGCATCGGCCAGAAATGATTATGCCAGCAACATGATTTGCATCATGCATGATGATGGCTATCAGGTCGCGCCTATGGCCACCGACGCGCTTGCAAACAGCATCGGTAAGGATTTACGTAAAGAAGCCCGTGAACTGGTCTTTGAGCAGCTTATGGAGCGCCACCTGAGTGTCGATACTCCTGACCAGGCCGAACACGATGAGTTGATAAAAAAACGCACCCTGTCCCTGGATGAGCAGGCCCAGCTGGTCCGCTGGGACATCGAAAAGGAGCTGCAGCTGGATGTCGACGAGGTGGCGTTAAAATTCTATTTCGACGGCGGCCTGAAAAAAGTGCGCCTGTTTGAAACCATGCAGCTGGATGAGATAACCGCCCGTCGCCTTGACCGTGAAGAAGCGTTGATTCACTTTACCTACGCTTATCGCGTTGCCGGAAGATGGCAGCAGTTCGTCACTACGGCCATGACGCGGGAACAGGCCGACGCAGAGTTCCAGGCTAAATTCCCGGCCATAACCGATTACCGAGTGAAATCGACCCCTGCTGTTGAGATAGGCATGCGTGGTTTCTACACCCTCAAATCGGCGACGCTGCAGCAGTACTTCCGCGACTGCGGTATCGATCCAAAAACCCTGGAAGGTGAAGCAGACATGGACGCCCTCAAACGCGCCAGAGATAACCTGCTCACGCCGGAACGGCGCGATCTGCTAAACAACGTTTTACGCATCGGCGGCTTCAACACAGAGAAAGGCAAGAAGAAAGCGCCTGCAGACCTCTGCATAGGCATCCTGGAGTCTATGGGGCTATCCAGTAAGACCAGACGCGCCAGAGACGGCGATGCACGCCCCACGATGCGTTCCATTGACCCGGACTCGGTCGAGTTCCTCATGAATATCGTGGAGAAGCGCCGCGAGGCCGGTTTATCAATTCACGCACGTAAGGTGGAAAAAACCACCATCGAAGTGGATCGCGATTTGGATCTAAATATAGATATACATGGTAACCCTCGATCCAAAACAGAGCACGTTCCGGACGCCCCACAATCAGTAATTATCCAGGCACTGGAGGCTATCCCGGTGGCGGTACCGGAGGCGTGGGCGGAGAACGCGTTGCCAGCAACCGAAATGGAGGCGGTACGCCTGTGGCCAGTGGCCAGCATCGCGAGAACGTTCGCCTCGCTGTACATGACCGAATTTATGGACCTGCTATCAGTACGCGAAATAAGGCTGCTGAAAGCGTTTCTAAGCCAGCGGCAAGCCGTGGCGATATAA"
    Private Const _repASC101ts1 As String = "ATGTCTGAATTAGTTGTTTTCAAAGCAAATGAACTAGCGATTAGTCGCTATGACTTAACGGAGCATGAAACCAAGCTAATTTTATGCTGTGTGGCACTACTCAACCCCACGATTGAAAACCCTACAAGGAAAGAACGGACGGTATCGTTCACTTATAACCAATACGTTCAGATGATGAACATCAGTAGGGAAAATGCTTATGGTGTATTAGCTAAAGCAACCAGAGAGCTGATGACGAGAACTGTGGAAATCAGGAATCCTTTGGTTAAAGGCTTTGAGATTTTCCAGTGGACAAACTATGCCAAGTTCTCAAGCGAAAAATTAGAATTAGTTTTTAGTGAAGAGATATTGCCTTATCTTTTCCAGTTAAAAAAATTCATAAAATATAATCTGGAACATGTTAAGTCTTTTGAAAACAAATACTCTATGAGGATTTATGAGTGGTTATTAAAAGAACTAACACAAAAGAAAACTCACAAGGCAAATATAGAGATTAGCCTTGATGAATTTAAGTTCATGTTAATGCTTGAAAATAACTACCATGAGTTTAAAAGGCTTAACCAATGGGTTTTGAAACCAATAAGTAAAGATTTAAACACTTACAGCAATATGAAATTGGTGGTTGATAAGCGAGGCCGCCCGACTGATACGTTGATTTTCCAAGTTGAACTAGATAGACAAATGGATCTCGTAACCGAACTTGAGAACAACCAGATAAAAATGAATGGTGACAAAATACCAACAACCATTACATCAGATTCCTACCTACATAACGGACTAAGAAAAACACTACACGATGCTTTAACTGCAAAAATTCAGCTCACCAGTTTTGAGGCAAAATTTTTGAGTGACATGCAAAGTAAGTATGATCTCAATGGTTCGTTCTCATGGCTCACGCAAAAACAACGAACCACACTAGAGAACATACTGGCTAAATACGGAAGGATCTGA"
    Private Const _repASC101ts2 As String = "ATGTCTGAATTAGTTGTTTTCAAAGCAAATGAACTAGCGATTAGTCGCTATGACTTAACGGAGCATGAAACCAAGCTAATTTTATGCTGTGTGGCACTACTCAACCCCACGATTGAAAACCCTACAAGGAAAGAACGGACGGTATCGTTCACTTATAACCAATACGCTCAGATGATGAACATCAGTAGGGAAAATGCTTATGGTGTATTAGCTAAAGCAACCAGAGAGCTGATGACGAGAACTGTGGAAATCAGGAATCCTTTGGTTAAAGGCTTTGAGATTTTCCAGTGGACAAACTATGCCAAGTTCTCAAGCGAAAAATTAGAATTAGTTTTTAGTGAAGAGATATTGCCTTATCTTTTCCAGTTAAAAAAATTCATAAAATATAATCTGGAACATGTTAAGTCTTTTGAAAACAAATACTCTATGAGGATTTATGAGTGGTTATTAAAAGAACTAACACAAAAGAAAACTCACAAGGCAAATATAGAGATTAGCCTTGATGAATTTAAGTTCATGTTAATGCTTGAAAATAACTACCATGAGTTTAAAAGGCTTAACCAATGGGTTTTGAAACCAATAAGTAAAGATTTAAACACTTACAGCAATATGAAATTGGTGGTTGATAAGCGAGGCCGCCCGACTGATACGTTGATTTTCCAAGTTGAACTAGATAGACAAATGGATCTCGTAACCGAACTTGAGAACAACCAGATAAAAATGAATGGTGACAAAATACCAACAACCATTACATCAGATTCCTACCTACGTAACGGACTAAGAAAAACACTACACGATGCTTTAACTGCAAAAATTCAGCTCACCAGTTTTGAGGCAAAATTTTTGAGTGACATGCAAAGTAAGTATGATCTCAATGGTTCGTTCTCATGGCTCACGCAAAAACAACGAACCACACTAGAGAACATACTGGCTAAATACGGAAGGATCTGA"
End Class

Public Class NativeHost
    Public Shared ReadOnly Property NativeHosts As List(Of Nuctions.Host)
        Get
            Return New List(Of Nuctions.Host) From {invitro, invivo, DH5α, TOP10, MG1655, DH10B, JM109, BL21, BW25141, EC100DPir, EC100DPir116, S17_1, S17_1Pir}
        End Get
    End Property
    Public Shared ReadOnly Property invitro As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "in vitro"
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property invivo As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "in vivo"
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property DH5α As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli DH5α"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property TOP10 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli TOP10"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property MG1655 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli MG1655"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property DH10B As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli DH10B"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property JM109 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli JM109"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property BL21 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli BL21"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property BW25141 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli BW25141"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "R6Kγ"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property EC100DPir As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli EC100D Pir"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "R6Kγ"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property EC100DPir116 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli EC100D Pir116"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "R6Kγ"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property S17_1 As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli S17-1"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Conjugation, .Parameters = "OriTR"})
            Return h
        End Get
    End Property
    Public Shared ReadOnly Property S17_1Pir As Nuctions.Host
        Get
            Dim h As New Nuctions.Host
            h.Name = "E. coli S17-1 Pir"
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "p15a"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "pUC"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Primase, .Parameters = "R6Kγ"})
            h.BioFunctions.Add(New Nuctions.FeatureFunction With {.BioFunction = Nuctions.FeatureFunctionEnum.Conjugation, .Parameters = "OriTR"})
            Return h
        End Get
    End Property
End Class